// todolist/src/index.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as SingleSpaReact from 'single-spa-react';

import "@babel/polyfill";

import App from './App';

const reactLifecycles = (SingleSpaReact as any).default({
  React,
  ReactDOM,
  domElementGetter,
  rootComponent: App,
});

const MICROSERVICE_INIT_OPTIONS : {
  container?: any,
} = { };


export const bootstrap = [
  reactLifecycles.bootstrap,
];

export const mount = [
  (props: any) => {
    Object.assign(MICROSERVICE_INIT_OPTIONS, props)
    return reactLifecycles.mount(props);
  },
];

export const unmount = [
  reactLifecycles.unmount,
];

function domElementGetter() {
  return document.getElementById(MICROSERVICE_INIT_OPTIONS.container);
}

// angular-service/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import singleSpaAngular from 'single-spa-angular';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(console.error);

const MICROSERVICE_INIT_OPTIONS: {
  container?: any,
} = { };

const ngLifecycles = singleSpaAngular({
  domElementGetter,
  mainModule: AppModule,
  angularPlatform: platformBrowserDynamic(),
  template: `<app-root />`,
})

export const bootstrap = [ ngLifecycles.bootstrap ];

export const mount = [
  (props) => {
    Object.assign(MICROSERVICE_INIT_OPTIONS, props);
    return ngLifecycles.mount(props);
  },
];

export const unmount = [ ngLifecycles.unmount ];

function domElementGetter() {
  return document.getElementById(MICROSERVICE_INIT_OPTIONS.container);
}
